server:
  port: 8021 #服务端口

spring:
  application:
    name: wxdc-config  #服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaopinglin/config-manage.git #git https地址
          username: 137708567@qq.com
          password: Lxp123456
          search-paths: wxdc-config #搜索改文件夹下的配置文件
          basedir: C:/ConfigManage/basedir #本地仓库地址
  rabbitmq:
    host: 180.76.97.214  #rabbitmq 地址
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port} #在Eureka 服务列表里显示的服务名称
    prefer-ip-address: true #访问的路径变为 IP 地址
  client:
    service-url:
      defaultZone: http://wxdc-eureka:8011/eureka/  #Eureka服务注册中心地址

management:
  security:
    enabled: false